button-component.html
- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
모바일 퍼스트 개발에 필요한 버튼 컴포넌트 파일 생성
resolves 1
=> feat: 버튼컴포넌트 초안 생성

src/components/subtitle/subtitle-component.css, src/components/subtitle/subtitle-component.html
모바일 기준 소제목 컴포넌트 제작
resolves #4
=> feat: 소제목 컴포넌트 생성

src/components/aboutme/aboutme-component.css, src/components/aboutme/aboutme-component.html
=> faet: 모바일 about me 컴포넌트 생성

src/components/references/references-component.css, src/components/references/references-component.html
=> feat : references 컴포넌트 생성

src/components/gallery/gallery-component.css, src/components/gallery/gallery-component.html
어바웃 상세페이지 GALLERY 컴포넌트 제작
resolves #23
=> feat : gallery 컴포넌트 제작

src/components/portfolio/portfolio-component.css, src/components/portfolio/portfolio-component.html
- [] 커밋 메시지 컨벤션에 맞게 작성했습니다.
about me 상세페이지 portfolio 컴포넌트 제작
resolves #24
=> feat : portfolio 컴포넌트 제작

src/components/aboutme/aboutme-component.css, src/components/aboutme/aboutme-component.html
aboutme-component (추가작업
resolves #19
=> feat: aboutme-component (추가작업)

src/components/home/home.css, src/components/home/home.html, src/components/home/home.js
home 틀 구현 (사용하세요)
resolves #32
=> feat:home 틀 구현

src/components/footer/footer.css
footer에 남색계열 색상추가 및 height 축소
resolves #
=> feat : footer update

index.html, package-lock.json, package.json, src/components/aboutme/aboutme-component.html, src/components/button/button-component.html, src/components/footer/footer.html, src/components/gallery/gallery-component.html, src/components/home/home.css, src/components/home/home.html, src/components/portfolio/portfolio-component.html, src/components/references/references-component.html, src/components/subtitle/subtitle-component.html, src/main.js, src/pages/References/references.html, src/style.css, vite.config.js
vite 개발 환경 구성, index.html 작업
resolves #
=> feat: index.html 1차 작업

src/pages/gallery/gallery.css, src/pages/gallery/gallery.html
main.js 코드 줄 삭제, alt 텍스트 변경
resolves #55
=> Refactor 55/gallery

src/pages/References/references.css, src/pages/References/references.html
nav 링크 연결 및 content 마진 수정
resolves #57
=> refactor: nav 링크 추가, content margin 변경

src/pages/gallery/gallery.css
=> styles: footer 수정

src/style.css
style.css about-detail.css wprj
resolves #
=> refactor: style.css about-detail.css 제거

src/pages/home/home.css, src/pages/home/home.html
gallery 이미지 추가 및 about me 텍스트 정렬
resolves #
=> refactor: gallery 이미지 추가

src/pages/home/home.css, src/pages/home/home.html
전체보기 버튼 추가 및 메인 화면 메뉴 삭제
resolves #
=> refactor: button

src/pages/about-detail/haemin/haeabout.html, src/pages/about-detail/jungwoo/jungabout.html, src/pages/about-detail/sugon/suabout.html, src/pages/about-detail/yuha/yuabout.html
=> refactor: aboutme 상세페이지 nav 링크 연결

src/pages/home/home.html
=> refactor: home.html 링크 수정 완료

src/pages/about-detail/haemin/haeabout.html, src/pages/about-detail/jungwoo/jungabout.html, src/pages/about-detail/sugon/suabout.html, src/pages/about-detail/yuha/yuabout.html
=> refactor: aboutme 상세페이지 aboutme 버튼 링크 추가

src/pages/gallery/gallery.html
=> refactor: gallery home 로고 변경 , about 링크 제거

src/pages/References/references.html
about-detail 변경에 따른 링크 수정
resolves #
=> refactor: about-detail 링크 수정

src/pages/about-detail/haemin/haeabout.html, src/pages/about-detail/jungwoo/jungabout.css, src/pages/about-detail/jungwoo/jungabout.html, src/pages/about-detail/sugon/suabout.html, src/pages/about-detail/yuha/yuabout.html
about-detail (겹침수정)
resolves #
=> refactor : about-detail (겹침수정)

index.html, src/pages/about-detail/haemin/haeabout.html, src/pages/about-detail/jungwoo/jungabout.html, src/pages/about-detail/sugon/suabout.html, src/pages/home/home.html
=> refactor: index.html, about me 상세페이지 타이틀 수정

src/pages/about-detail/haemin/haeabout.css, src/pages/about-detail/haemin/haeabout.html, src/pages/about-detail/jungwoo/jungabout.css, src/pages/about-detail/jungwoo/jungabout.html, src/pages/about-detail/sugon/suabout.css, src/pages/about-detail/sugon/suabout.html, src/pages/about-detail/yuha/yuabout.css, src/pages/about-detail/yuha/yuabout.html
refactor : about-detail (오류수정)
resolves #
=> refactor : about-detail (오류수정)

src/pages/gallery/gallery.html
figcaption 과 비슷한 alt 텍스트 수정
resolves #101
=> refactor: 접근성 -  figcaption 과 비슷한 alt 텍스트 수정

src/pages/home/home.html
=> refactor: alt 수정

index.css, index.html
overflow 코드 추가, 보고서 추가 (최종배포링크 추가 전)
resolves #104
=> refactor: overflow 코드 추가, 보고서 추가 (최종배포링크 추가 전)

README.md
- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
resolves #
=> refactor: readme 팀원소개 추가
